version: '2'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:latest"
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres
  web:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    command: ["npm", "start"]
